### ISSUE TITLE
Support `__debug__` variable

### ISSUE THREAD

**Issue by sobolevn** [orsinium/deal#3]
In some cases relying on `__debug__` variable can be a game changer. 

## Rationale 

Using contracts gives significant overhead. If this function is a hot-path for some business logics (and it generally is, that why you want to make it safe) this can be a huge performance problem.

That where `__debug__` kicks in.

When running on optimized mode we expect that this is a production environment.
It changes several things for us:
1. We now know that we do not want contract to change any behavior
2. We now know that we do not want any overhead for our system

## Solution

I suggest to copy the idea of this package: https://github.com/deadpixi/contracts
It just returns the function itself for the decorator when `__debug__` is `True`.

## Considerations

Some people may rely on contracts in production. So, we can make this feature configurable.
This, however, may cause different use-cases for different users. 

But, in my opinion the best practice is: do not rely on these checks in production.
Use typing and tests (always include property-based tests for contracts!) to find any logics breaches early.

**Comment by orsinium** [comment]
Thank you for good proposal. Sometimes contracts suitable for validation input from external source. Yes, on all environments. I'll make it configurable.

**Comment by orsinium** [comment]
Added `debug` parameter for contract definition. See [new section in readme](https://github.com/orsinium/deal#disable-contracts-on-production) for more information.
